### ISSUE TITLE
a2oj not working

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [earthshakira/a2oj-clientside#1]
@earthshakira

**Comment by Ayush0Chaudhary** [comment]
![image](https://github.com/earthshakira/a2oj-clientside/assets/95746190/f216dc95-2392-4966-b5c3-55aeded849be)

**Comment by earthshakira** [comment]
Oh cool,will check sometime when free, meanwhile feel free to open a PR if required

**Comment by Ayush0Chaudhary** [comment]
sorry codeforces was down
